### ISSUE TITLE
站长组件规范自动化检查标准讨论

### ISSUE THREAD

**Issue by tfciw** [mipengine/mip2-extensions-platform#307]

**Comment by VenyXiong** [comment]
这里我补充一些背景和说明：
## 自动化规范检查和校验
目前mip在对下游的开发者和合作方而言，在审核标准上有点过于严格了，并且在这一块付出了很大的人力成本，但是做为一个开发框架和技术解决方案，这些都应该是由工具在编译阶段或者开发阶段去完成的，如果某项规则我们禁止其使用，那么在开发、编译、调试的过程中就能够暴露出来，而不是在提交完代码之后靠我们人肉去review。
所以我们需要review下我们当前对下游开发者的一些规范限制是否合理， 去除不合理的，新增合理的。
这些规范应该满足以下几点：
- 违反规范会造成运行时出bug
- 违反会对mip和搜索造成较大的安全隐患
- 违反会对mip的性能造成较大的影响
- 可以被机器所检测
- 对于MUST NOT 的一些场景，需要给出替代的方案

## 上线流程
对于第三方开发者来说，上线流程是他们比较关注的，第三方开发者希望能够掌握自主上线权限，我们希望尽量减少在这块的人力成本消耗，所以这里需要有一套流程提供给开发者，使得他们可以自主的完成他们组件代码的编译、发布和上线。而不需要强依赖于mip值周。

**Comment by zoumiaojiang** [comment]
参考：https://github.com/mipengine/mip2/issues/449
