### ISSUE TITLE
站点组件的自动审核与发布

### ISSUE THREAD

**Issue by tayqassqan** [mipengine/mip2-extensions-platform#347]
完善当前的组件提交上线流程，支持开发者开发提交后自动审核并上线。同时保证以下功能：

1. 安全性：自动化流程中必须执行安全性校验；
2. 状态提示：发布后上线中的流程和状态；
3. 时效性：1小时内完成发布和上线；

**Comment by regedit** [comment]
v2的代码多久才审核一次啊？我上周提交PR一直没有审核啊

**Comment by zoumiaojiang** [comment]
每天都会有审核，通常在 4 点前完成审核，请随时关注 github 动态，审核人力有限，为了提升审核通过率，提交代码请注意按照 mip 规范先进性自查。
