### ISSUE TITLE
异步请求处理数据，都要写组件，有些不方便

### ISSUE THREAD

**Issue by FeliciaLFF** [mipengine/mip2-extensions-platform#502]
如：http://mipmobi002.no16.35nic.com/open_webapi/MofineApi.asmx/GetIndexMenu?editionId=1&intTop=4接口 渲染列表，"wapMenuIcon":"|/upload/wap_menuconfig/2019011609515351.png"  字段需要处理，就要写组件，或者，根据某个isshow:"" 判断是否显示等

**Comment by PengXing** [comment]
简单的数据数据处理操作可以通过 `mip-script` 来完成，https://www.mipengine.org/v2/components/dynamic-content/mip-script.html，再通过数据绑定的方式让组件使用
