### ISSUE TITLE
mip-ad 组件同一个广告id 在同一个页面中投放多次，会出现不展示的情况

### ISSUE THREAD

**Issue by hejieye** [mipengine/mip2-extensions-platform#550]
第一个投放的位置能展示，第二个投放的位置概率性展示。 在后面投放的广告是不展示的。
希望一个广告id根据 mip-ad 组件能在同一个页面中多次投放
tip：同一个广告ID

**Comment by Ricardo-Li** [comment]
你好，官方组件相关问题，请前往 [mip2-extensions](https://github.com/mipengine/mip2-extensions/issues) 仓库提交并详细描述问题。
