### ISSUE TITLE
手机站已使用mip-list组件，该组件src属性必须是https，能否支持http?

### ISSUE THREAD

**Issue by FeliciaLFF** [mipengine/mip2-extensions-platform#558]
例子：https://mipmobi009.no16.35nic.com/mip/templates/default/index.html?menuIndexVar=menu_151&editionId=1

**Comment by Ricardo-Li** [comment]
你好，官方组件相关问题，请前往 [mip2-extensions](https://github.com/mipengine/mip2-extensions/issues) 仓库提交并详细描述问题。
