### ISSUE TITLE
Deploy logs are currently unavailable. We are working on resolving the issue.

### ISSUE THREAD

**Issue by TulipaGesneriana** [mipengine/mip2-extensions-platform#623]
Deploy logs are currently unavailable. We are working on resolving the issue.   
这个错误怎么解决啊。。。。。。头疼。。

_Originally posted by @TulipaGesneriana in https://github.com/mipengine/mip2-extensions-platform/pull/614#issuecomment-492160717_

**Comment by zoumiaojiang** [comment]
是哪里报的错误呢？是 netlify 吗？

**Comment by TulipaGesneriana** [comment]
> 是哪里报的错误呢？是netlify吗？

是的。卡在这里了 本地运行的时候没抛异常

**Comment by kevinzhao2233** [comment]
好像是被墙了，，
